Feature/shadow shape puzzle
DanielNijkamp/PVB pull request #13
Opened 2024-04-12 08:01 UTC by RossTubes

I made a raycast detection system to check rather or not the shadow puzzle is complete, if the raycast does hit all the required puzzle pieces and does not hit the shadow shape behind means the shadow is succesfully filled in and the puzzle is then completed. 

When the puzzle is completed then the shapematcher script checks all pieces and freezes the position so that the puzzle cannot be broken again.

2024-04-12 16:14 UTC, DanielNijkamp requested changes
Slechte code. 

Stop met ChatGPT gebruiken als het slechte code opleverd. Kijk echt goed naar de code conventie en lees het goed. Kleine dingen zoals: Geen debug.logs, Access modifiers, Pascal vs camelCasing zijn echt basis dingen die nu foutloos gedaan moeten worden.

2024-04-12 16:14 UTC, DanielNijkamp commented on Assets/Scripts/Player/ShapeMatcher.cs
> +    }
```suggestion
```

2024-04-12 16:14 UTC, DanielNijkamp commented on Assets/Scripts/ShadowPuzzle/PilarCheck.cs
> +public class PilarCheck : MonoBehaviour
```suggestion
public sealed class Pillar : MonoBehaviour
```
Miss een betere naam

2024-04-12 16:14 UTC, DanielNijkamp commented on Assets/Scripts/ShadowPuzzle/PilarCheck.cs
> +    void OnTriggerEnter(Collider other)
```suggestion
    private void OnTriggerEnter(Collider other)
```
altijd access modifier hebben

2024-04-12 16:14 UTC, DanielNijkamp commented on Assets/Scripts/ShadowPuzzle/PilarCheck.cs
> +    public void FreezeMovement(GameObject obj)
```suggestion
    private void Lock()
```

2024-04-12 16:14 UTC, DanielNijkamp commented on Assets/Scripts/ShadowPuzzle/PilarCheck.cs
> +    public GameObject pilar;
```suggestion
    public bool Completed { get; private set; }
    
    [SerializeField] private Transform lockPosition;
    [SerializeField] private GameObject pillar;
    
    [SerializeField] private UnityEvent onCompleted = new();
```
Paar dingen:

- Betere benamingen
- Denk aan access modifiers. niet alles moet public
- Completed moet ook private set sinds je niet wilt dat het van buiten aanpasbaar is.
- UnityEvent gebruiken om script los te koppelen

2024-04-12 16:14 UTC, DanielNijkamp commented on Assets/Scripts/ShadowPuzzle/PilarCheck.cs
> +        }
```suggestion
            Rigidbody rigidbody = pillar.GetComponent<Rigidbody>();
            if (rigidbody == null) return
            
                rigidbody.constraints = RigidbodyConstraints.FreezePositionX |
                                         RigidbodyConstraints.FreezePositionY |
                                         RigidbodyConstraints.FreezePositionZ;
            
        }
```
We hoeven geen gameobject mee te geven via the method we kunnen gewoon de gameobject gebruiken die in de class al opgeslages is bovenaan.

Je kan ook om de positie still te maken beter ook isKinematic gebruiken ipv manually alle posities te freezen.

2024-04-12 16:14 UTC, DanielNijkamp commented on Assets/Scripts/ShadowPuzzle/PilarCheck.cs
> +            pilarInPlace = true;
```suggestion
            Completed = true;
```

2024-04-12 16:14 UTC, DanielNijkamp commented on Assets/Scripts/Player/ShapeMatcher.cs
> +    }
```suggestion
```
Access modifier moet er altijd bij. 
Ook geen debug.logs
de rest van de code is ook boilerplate en is niet nodig

2024-04-12 16:14 UTC, DanielNijkamp commented on Assets/Scripts/Player/ShapeMatcher.cs
> +    }
```suggestion
    public void CheckCompletion()
    {
        if (pillars.All(x => x.Completed))
        {
            onCompletion?.Invoke()
        }
    }
```
Beter om niet de completion te checken in de update. deze method moet aangeroepen worden via een event elke keer als een pillar gecomplete word. hij checkt dan of de pillars completed zijn en dan roept hij event aan.

2024-04-12 16:14 UTC, DanielNijkamp commented on Assets/Scripts/Player/ShapeMatcher.cs
> +public class ShapeMatcher : MonoBehaviour
```suggestion
public sealed class PillarManager: MonoBehaviour
```

2024-04-12 16:14 UTC, DanielNijkamp commented on Assets/Scripts/Player/ShapeMatcher.cs
> +    public PilarCheck pilarCheck;
```suggestion
    [SerializeField] private Pillars[] pillars;
    [SerializeField] private UnityEvent onCompletion = new();
```
Simpele benamingen zijn beter leesbaar en alle booleans zijn nutteloos. we hoeven niet 4 booleans om deze class te markeren of iets klaar is. 
Ook UnityEvent gebruiken zodat we het samen met andere systemen kunnen gebruiken in een goede manier.

2024-04-15 11:22 UTC, DanielNijkamp requested changes
Nog paar dingen dan is het klaar

2024-04-15 11:22 UTC, DanielNijkamp commented on Assets/Scripts/ShadowPuzzle/PilarCheck.cs
> +public sealed class Pillars: MonoBehaviour
```suggestion
public sealed class Pillar: MonoBehaviour
```
Verander ook de file dat het de class matched.

2024-04-15 11:22 UTC, DanielNijkamp commented on Assets/Scripts/ShadowPuzzle/PilarCheck.cs
> +            }
```suggestion
            Rigidbody rigidbody = obj.GetComponent<Rigidbody>();
            if (rigidbody != null)
            {
                rigidbody.constraints = RigidbodyConstraints.FreezePositionX |
                                         RigidbodyConstraints.FreezePositionY |
                                         RigidbodyConstraints.FreezePositionZ;
            
```
Onnodige brackets weghalen

2024-04-15 11:22 UTC, DanielNijkamp commented on Assets/Scripts/Player/ShapeMatcher.cs
> +    [SerializeField] private Pillars[] pillars;
```suggestion
    [SerializeField] private Pillar[] pillars;
```

2024-04-15 11:22 UTC, DanielNijkamp commented on Assets/Scripts/ShadowPuzzle/PilarCheck.cs
> +            lock(other.gameObject);
```suggestion
            Lock(other.gameObject);
            onCompleted?.Invoke();
```

2024-04-15 11:26 UTC, RossTubes commented on Assets/Scripts/Player/ShapeMatcher.cs
> +    [SerializeField] private Pillars[] pillars;
changed!

2024-04-15 12:09 UTC, DanielNijkamp approved these changes
happi happi

2024-04-15 12:09 UTC, merged