Feature/player interactivity
DanielNijkamp/PVB pull request #14
Opened 2024-04-15 11:31 UTC by DanielNijkamp

Player can interact with Interactable with E and Square button
Player can grab objects with F and X button

2024-04-15 13:12 UTC, Kazuma-47 requested changes

2024-04-15 13:12 UTC, Kazuma-47 commented on Assets/Scripts/Framework/Events/EventTrigger.cs
> +//TODO: namespace
```suggestion
//TODO: namespace
```
is het af?

2024-04-15 13:12 UTC, Kazuma-47 commented on Assets/Scripts/Player/Interaction/Grabable.cs
> +//TODO: namespace
namespace missing habibi ::))

2024-04-15 13:12 UTC, Kazuma-47 commented on Assets/Scripts/Player/Interaction/Interactable.cs
> +//TODO: namespace
namespace

2024-04-15 13:31 UTC, bas-boop reviewed
Habibi wel goede code.

2024-04-15 13:31 UTC, bas-boop commented on Assets/Scripts/Framework/Events/EventTrigger.cs
> +    public class EventTrigger : MonoBehaviour
```suggestion
    public sealed class EventTrigger : MonoBehaviour
```

2024-04-15 13:31 UTC, bas-boop commented on Assets/Scripts/Framework/Events/EventTrigger.cs
> +            }
```suggestion
if (withTag && !other.CompareTag(tag)) return;

(onTriggerEnterWithInfo != null && supplyInfo ? onTriggerEnterWithInfo : onTriggerEnter)?.Invoke(other);
```
Niet getest, maar dit is meer DRY.

2024-04-15 13:31 UTC, bas-boop commented on Assets/Scripts/Framework/Events/EventTrigger.cs
> +        }
Maak het meer dry, maak een private functie voor de enter en exit.

2024-04-15 13:31 UTC, bas-boop commented on Assets/Scripts/Player/Interaction/Grab.cs
> +            if (inRange.Contains(grabable)) return;
```suggestion
if (!target.TryGetComponent<Grabable>(out var grabable)
|| grabable.IsOwned
|| inRange.Contains(grabable)) return;

```

2024-04-15 13:31 UTC, bas-boop commented on Assets/Scripts/Player/Interaction/Grabable.cs
> +        private new Collider collider;
```suggestion
        private Rigidbody rigidbody;
        private Collider collider;
```
Waarom `new` keyword er bij? Je pakt ze toch all in `Awake`.

2024-04-15 13:31 UTC, bas-boop commented on Assets/Scripts/Player/Interaction/Grabable.cs
> +    [RequireComponent(typeof(Rigidbody))]
```suggestion
    [RequireComponent(typeof(Rigidbody), typeof(Collider))]
```

2024-04-15 13:34 UTC, bas-boop commented on Assets/Scripts/Framework/Events/EventTrigger.cs
> +    public class EventTrigger : MonoBehaviour
Oepsie, bedoelde `abstract`.

2024-04-15 13:41 UTC, DanielNijkamp commented on Assets/Scripts/Framework/Events/EventTrigger.cs
> +    public class EventTrigger : MonoBehaviour
Deze word ook aleenstaand gebruikt dus nee >:)

2024-04-16 11:18 UTC, Kazuma-47 approved these changes
Helemaal mooi habibi

2024-04-16 11:19 UTC, merged