tex added for the split room
DanielNijkamp/PVB pull request #15
Opened 2024-04-19 07:57 UTC by falko124

2024-04-19 09:17 UTC, DanielNijkamp requested changes
- Prefab hernoemen naar "Split Rooms"
- Misschien alle stones mergen naar 1 object zodat we in unity niet 300 stone objecten hebben. 
- Alle child objecten van de split room ook hoofdletters geven en groepen. alle deuren moeten onder een deur parent object bijv.

2024-04-19 10:42 UTC, Eliza-van-bokhoven reviewed
Inprecipe is "Baseroom_Splitroom_V2" correct via de naming conventions. Maar as Daniel liever wilt dat hij Splitrooms heet maakt mij dat niet uit.

Verder ben ik het wel eens met de comments van daniel als dit er niet voor zorgt dat je de UV weer opnieuw moet doen ect. 

Geen andere comments.

2024-04-19 11:09 UTC, DanielNijkamp commented
> Inprecipe is "Baseroom_Splitroom_V2" correct via de naming conventions. Maar as Daniel liever wilt dat hij Splitrooms heet maakt mij dat niet uit.
> 
> Verder ben ik het wel eens met de comments van daniel als dit er niet voor zorgt dat je de UV weer opnieuw moet doen ect.
> 
> Geen andere comments.

Ik wou aleen dat de naam wat generieker is ipv specifiek voor de lights & Shadows puzzle. maar als het volgens de conventie `Baseroom_Splitroom_V2` moet zijn dan zou ik het wel zo veranderen dat het de conventie volgt

2024-04-19 11:33 UTC, Eliza-van-bokhoven approved these changes
looks good.

2024-04-22 07:57 UTC, DanielNijkamp approved these changes

2024-04-22 07:57 UTC, merged