Feature/puzzle1
DanielNijkamp/PVB pull request #16
Opened 2024-04-19 14:04 UTC by RossTubes

I fixed the lights & shadow puzzle and tested it so it now works, the pillars can now be locked in place and when all four pieces are in the right place the shadow will show up and locks the pillars in place with rotation and position this way the puzzle cannot be broken after. We can use the event of the completion to make either a door open or show an victory message.

2024-04-22 09:52 UTC, Kazuma-47 approved these changes
helemaal mooi

2024-04-22 13:37 UTC, Kazuma-47 requested changes
kleine bug want als je de objecten met als de speler op pak heb ik 2 dingen gevonden: 
De rotatatie van de objecten word niet bij gehouden waardoor de shaduw er niet correct uitziet

ook zit van de objecten/pillars de pivots niet goed
de speler pivot staat ook niet helemaal goed waardoor de speler door de vloer clipt 
het liefst moet de pivot van een object en de speler op de vloer zodat als ze worden gespawned niks onder de map komt

2024-04-25 14:33 UTC, Kazuma-47 submitted a review, later dismissed
looks good :))

2024-04-25 14:39 UTC, Kazuma-47 approved these changes
updated branch with develop

2024-04-25 14:40 UTC, DanielNijkamp approved these changes

2024-04-25 14:40 UTC, merged