Feature/game flow
DanielNijkamp/PVB pull request #19
Opened 2024-04-23 11:30 UTC by DanielNijkamp

2024-04-25 08:03 UTC, DanielNijkamp commented
Only files to be added: Room spawning script/game state manager

2024-04-25 09:11 UTC, Kazuma-47 requested changes

2024-04-25 09:11 UTC, Kazuma-47 commented on Assets/Scripts/Framework/SceneLoader.cs
> +public class SceneLoader : MonoBehaviour
```suggestion
public sealed class SceneLoader : MonoBehaviour
```

2024-04-25 09:11 UTC, Kazuma-47 commented on Assets/Scripts/Gameflow/Corridor.cs
> +
```suggestion
```

2024-04-25 09:11 UTC, Kazuma-47 commented on Assets/Scripts/UI/Main Menu/MenuHandler.cs
> +public class MainMenuHandler : MonoBehaviour
```suggestion
public  sealed class MainMenuHandler : MonoBehaviour
```

2024-04-25 09:17 UTC, Kazuma-47 submitted a review, later dismissed
lookin good

2024-05-06 09:06 UTC, Kazuma-47 approved these changes

2024-05-06 09:07 UTC, merged