Wall torch added
DanielNijkamp/PVB pull request #30
Opened 2024-05-07 12:25 UTC by falko124

2024-05-07 13:09 UTC, Eliza-van-bokhoven requested changes
**!! Don' t try and merge into the masters branch, Change it to develop !!**

- Move the torch FBX into the correct map.
- Rename the model following the naming conventions guide

2024-05-13 13:41 UTC, DanielNijkamp approved these changes, later dismissed

2024-05-13 13:49 UTC, Eliza-van-bokhoven requested changes
Map still needs to be changed!
![2](https://github.com/DanielNijkamp/PVB/assets/83960112/7b787342-8bec-43ac-ae0f-a07a3ca9f97f)
![1](https://github.com/DanielNijkamp/PVB/assets/83960112/6c22b5a1-99f7-442a-852c-d30de2e846cb)

2024-05-14 07:57 UTC, Eliza-van-bokhoven approved these changes

2024-05-14 07:58 UTC, merged